[book]
title = "Computer</br>Engineering"
author = "Quentin Wach"
description = "Notes on computer engineering. How to go from application to custom computer design."

[output.html]
theme = "theme/azaleabook-theme"
default-theme = "azaleabook-darks"
preferred-dark-theme = "azaleabook-dark"
mathjax-support = true