[book]
title = "The Hack Computer Architecture"
author = "Quentin Wach"
description = "Verilog implementation and detailed explanation of the Hack computer architecture with the help of Logisim, Icarus Verilog, and GTKWave."

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
mathjax-support = true
